inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'db/**/*'
    - 'config/initializers/*'
    - 'Guardfile'


Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'spec/rails_helper.rb'
    - 'bin/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
